#ifndef QNRBFFORMAT_XSREVERBPRESET_H
#define QNRBFFORMAT_XSREVERBPRESET_H

#include <QDataStream>

#include "qnrbf_global.h"

QNRBF_BEGIN_NAMESPACE

// SingingTool.Library.Audio.ReverbPreset
enum XSReverbPreset {
    NONE = -1,
    DEFAULT,
    SMALLHALL1,
    SMALLHALL2,
    MEDIUMHALL1,
    MEDIUMHALL2,
    LARGEHALL1,
    LARGEHALL2,
    SMALLROOM1,
    SMALLROOM2,
    MEDIUMROOM1,
    MEDIUMROOM2,
    LARGEROOM1,
    LARGEROOM2,
    MEDIUMER1,
    MEDIUMER2,
    PLATEHIGH,
    PLATELOW,
    LONGREVERB1,
    LONGREVERB2,
};

QNRBF_END_NAMESPACE

#endif // QNRBFFORMAT_XSREVERBPRESET_H
